#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x873AC3459BBCF5C0 (nicolas.fella@kdab.com)
#
Name     : kdeconnect-kde
Version  : 1.3.4
Release  : 1
URL      : https://download.kde.org/stable/kdeconnect/1.3.4/kdeconnect-kde-1.3.4.tar.xz
Source0  : https://download.kde.org/stable/kdeconnect/1.3.4/kdeconnect-kde-1.3.4.tar.xz
Source99 : https://download.kde.org/stable/kdeconnect/1.3.4/kdeconnect-kde-1.3.4.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: kdeconnect-kde-bin = %{version}-%{release}
Requires: kdeconnect-kde-data = %{version}-%{release}
Requires: kdeconnect-kde-lib = %{version}-%{release}
Requires: kdeconnect-kde-license = %{version}-%{release}
Requires: kdeconnect-kde-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : kwayland-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : pkg-config
BuildRequires : qca-qt5-dev
BuildRequires : qtbase-dev mesa-dev

%description
This simple plugin will just listen to "kdeconnect.telephony" like the telephony
plugin does. It reads the field "event", to see if it is "ringing" or "talking"
and then pauses all the music/video players reachable through MPRIS. When the
same kind of package is received but the boolean "isCancel" is set to true, it
will resume the playback of all the paused sources.

%package bin
Summary: bin components for the kdeconnect-kde package.
Group: Binaries
Requires: kdeconnect-kde-data = %{version}-%{release}
Requires: kdeconnect-kde-license = %{version}-%{release}

%description bin
bin components for the kdeconnect-kde package.


%package data
Summary: data components for the kdeconnect-kde package.
Group: Data

%description data
data components for the kdeconnect-kde package.


%package doc
Summary: doc components for the kdeconnect-kde package.
Group: Documentation

%description doc
doc components for the kdeconnect-kde package.


%package lib
Summary: lib components for the kdeconnect-kde package.
Group: Libraries
Requires: kdeconnect-kde-data = %{version}-%{release}
Requires: kdeconnect-kde-license = %{version}-%{release}

%description lib
lib components for the kdeconnect-kde package.


%package license
Summary: license components for the kdeconnect-kde package.
Group: Default

%description license
license components for the kdeconnect-kde package.


%package locales
Summary: locales components for the kdeconnect-kde package.
Group: Default

%description locales
locales components for the kdeconnect-kde package.


%prep
%setup -q -n kdeconnect-kde-1.3.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557277068
mkdir -p clr-build
pushd clr-build
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1557277068
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kdeconnect-kde
cp COPYING %{buildroot}/usr/share/package-licenses/kdeconnect-kde/COPYING
pushd clr-build
%make_install
popd
%find_lang kdeconnect-cli
%find_lang kdeconnect-core
%find_lang kdeconnect-kcm
%find_lang kdeconnect-kded
%find_lang kdeconnect-kio
%find_lang kdeconnect-plugins
%find_lang plasma_applet_org.kde.kdeconnect
%find_lang kdeconnect-urlhandler

%files
%defattr(-,root,root,-)
/usr/lib64/libexec/kdeconnectd

%files bin
%defattr(-,root,root,-)
/usr/bin/kdeconnect-cli
/usr/bin/kdeconnect-handler
/usr/bin/kdeconnect-indicator

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.kdeconnect.kcm.desktop
/usr/share/applications/org.kde.kdeconnect.nonplasma.desktop
/usr/share/applications/org.kde.kdeconnect.telhandler.desktop
/usr/share/dbus-1/services/org.kde.kdeconnect.service
/usr/share/icons/hicolor/128x128/apps/kdeconnect.png
/usr/share/icons/hicolor/16x16/apps/kdeconnect.png
/usr/share/icons/hicolor/22x22/apps/kdeconnect.png
/usr/share/icons/hicolor/256x256/apps/kdeconnect.png
/usr/share/icons/hicolor/32x32/apps/kdeconnect.png
/usr/share/icons/hicolor/32x32/status/laptopconnected.png
/usr/share/icons/hicolor/32x32/status/laptopdisconnected.png
/usr/share/icons/hicolor/32x32/status/laptoptrusted.png
/usr/share/icons/hicolor/32x32/status/smartphoneconnected.png
/usr/share/icons/hicolor/32x32/status/smartphonedisconnected.png
/usr/share/icons/hicolor/32x32/status/smartphonetrusted.png
/usr/share/icons/hicolor/32x32/status/tabletconnected.png
/usr/share/icons/hicolor/32x32/status/tabletdisconnected.png
/usr/share/icons/hicolor/32x32/status/tablettrusted.png
/usr/share/icons/hicolor/48x48/apps/kdeconnect.png
/usr/share/icons/hicolor/64x64/apps/kdeconnect.png
/usr/share/icons/hicolor/scalable/apps/kdeconnect.svgz
/usr/share/icons/hicolor/scalable/status/laptopconnected.svg
/usr/share/icons/hicolor/scalable/status/laptopdisconnected.svg
/usr/share/icons/hicolor/scalable/status/laptoptrusted.svg
/usr/share/icons/hicolor/scalable/status/smartphoneconnected.svg
/usr/share/icons/hicolor/scalable/status/smartphonedisconnected.svg
/usr/share/icons/hicolor/scalable/status/smartphonetrusted.svg
/usr/share/icons/hicolor/scalable/status/tabletconnected.svg
/usr/share/icons/hicolor/scalable/status/tabletdisconnected.svg
/usr/share/icons/hicolor/scalable/status/tablettrusted.svg
/usr/share/knotifications5/kdeconnect.notifyrc
/usr/share/kservices5/kcm_kdeconnect.desktop
/usr/share/kservices5/kdeconnect_pausemusic_config.desktop
/usr/share/kservices5/kdeconnect_runcommand_config.desktop
/usr/share/kservices5/kdeconnect_sendnotifications_config.desktop
/usr/share/kservices5/kdeconnect_share_config.desktop
/usr/share/kservices5/kdeconnectsendfile.desktop
/usr/share/kservices5/plasma-kdeconnect.desktop
/usr/share/kservicetypes5/kdeconnect_plugin.desktop
/usr/share/metainfo/org.kde.kdeconnect.kcm.appdata.xml
/usr/share/nautilus-python/extensions/kdeconnect-share.py
/usr/share/plasma/plasmoids/org.kde.kdeconnect/contents/ui/Battery.qml
/usr/share/plasma/plasmoids/org.kde.kdeconnect/contents/ui/DeviceDelegate.qml
/usr/share/plasma/plasmoids/org.kde.kdeconnect/contents/ui/FindMyPhone.qml
/usr/share/plasma/plasmoids/org.kde.kdeconnect/contents/ui/FullRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.kdeconnect/contents/ui/RemoteKeyboard.qml
/usr/share/plasma/plasmoids/org.kde.kdeconnect/contents/ui/Sftp.qml
/usr/share/plasma/plasmoids/org.kde.kdeconnect/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.kdeconnect/metadata.desktop
/usr/share/xdg/autostart/kdeconnectd.desktop

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/en/kdeconnect/index.cache.bz2
/usr/share/doc/HTML/en/kdeconnect/index.docbook

%files lib
%defattr(-,root,root,-)
/usr/lib64/libkdeconnectcore.so.1
/usr/lib64/libkdeconnectcore.so.1.3.4
/usr/lib64/libkdeconnectinterfaces.so.1
/usr/lib64/libkdeconnectinterfaces.so.1.3.4
/usr/lib64/libkdeconnectpluginkcm.so.1
/usr/lib64/libkdeconnectpluginkcm.so.1.3.4
/usr/lib64/qt5/plugins/kcm_kdeconnect.so
/usr/lib64/qt5/plugins/kdeconnect/kdeconnect_battery.so
/usr/lib64/qt5/plugins/kdeconnect/kdeconnect_clipboard.so
/usr/lib64/qt5/plugins/kdeconnect/kdeconnect_findmyphone.so
/usr/lib64/qt5/plugins/kdeconnect/kdeconnect_mousepad.so
/usr/lib64/qt5/plugins/kdeconnect/kdeconnect_mpriscontrol.so
/usr/lib64/qt5/plugins/kdeconnect/kdeconnect_notifications.so
/usr/lib64/qt5/plugins/kdeconnect/kdeconnect_pausemusic.so
/usr/lib64/qt5/plugins/kdeconnect/kdeconnect_ping.so
/usr/lib64/qt5/plugins/kdeconnect/kdeconnect_remotekeyboard.so
/usr/lib64/qt5/plugins/kdeconnect/kdeconnect_runcommand.so
/usr/lib64/qt5/plugins/kdeconnect/kdeconnect_screensaver_inhibit.so
/usr/lib64/qt5/plugins/kdeconnect/kdeconnect_sendnotifications.so
/usr/lib64/qt5/plugins/kdeconnect/kdeconnect_sftp.so
/usr/lib64/qt5/plugins/kdeconnect/kdeconnect_share.so
/usr/lib64/qt5/plugins/kdeconnect/kdeconnect_telephony.so
/usr/lib64/qt5/plugins/kdeconnect_pausemusic_config.so
/usr/lib64/qt5/plugins/kdeconnect_runcommand_config.so
/usr/lib64/qt5/plugins/kdeconnect_sendnotifications_config.so
/usr/lib64/qt5/plugins/kdeconnect_share_config.so
/usr/lib64/qt5/plugins/kdeconnectfileitemaction.so
/usr/lib64/qt5/plugins/kf5/kio/kdeconnect.so
/usr/lib64/qt5/qml/org/kde/kdeconnect/DBusProperty.qml
/usr/lib64/qt5/qml/org/kde/kdeconnect/PluginChecker.qml
/usr/lib64/qt5/qml/org/kde/kdeconnect/libkdeconnectdeclarativeplugin.so
/usr/lib64/qt5/qml/org/kde/kdeconnect/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kdeconnect-kde/COPYING

%files locales -f kdeconnect-cli.lang -f kdeconnect-core.lang -f kdeconnect-kcm.lang -f kdeconnect-kded.lang -f kdeconnect-kio.lang -f kdeconnect-plugins.lang -f plasma_applet_org.kde.kdeconnect.lang -f kdeconnect-urlhandler.lang
%defattr(-,root,root,-)

